
export const camelToKebab = (str: string) =>
  str.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);


export function sxToString(sx?: object): string {
  if (!sx) return "";

  return Object.entries(sx).map(([key, value]) => `${camelToKebab(key)}: ${value}`).join("; ");
}

type SxKeys =
  "width"
  | "height"
  | "gap"
  | "color"
  | "backgroundColor"
  | "paddingInline"
  | "padding"
  | "paddingTop"
  | "paddingBottom"
  | "paddingBlock"
  | "paddingLeft"
  | "paddingRight"
  | "margin"
  | "marginRight"
  | "marginLeft"
  | "marginTop"
  | "marginBottom"
  | "marginInline"
  | "marginBlock"
  | "display"
  | "position"
  | "top"
  | "right"
  | "left"
  | "bottom"
  | "flex"
  | "flexDirection"
  | "flexWrap"
  | "justifyContent"
  | "alignItems"
  | "alignContent"
  | "alignSelf"
  | "order"
  | "flexGrow"
  | "flexShrink"
  | "flexBasis"
  | "flexFlow"
  | "gridGap"
  | "gridRowGap"
  | "gridColumnGap"
  | "gridAutoFlow"
  | "gridAutoRows"
  | "gridAutoColumns"
  | "gridTemplateRows"
  | "gridTemplateColumns"
  | "gridTemplateAreas"
  | "gridArea"
  | "gridRowStart"
  | "gridColumnStart"
  | "gridRowEnd"
  | "gridColumnEnd"
  | "gridRow"
  | "gridColumn"
  | "justifySelf"
  | "placeSelf"
  | "zIndex"
  | "border"
  | "borderWidth"
  | "borderStyle"
  | "borderColor"
  | "borderTop"
  | "borderRight"
  | "borderBottom"
  | "borderLeft"
  | "borderRadius"
  | "borderTopLeftRadius"
  | "borderTopRightRadius"
  | "borderBottomRightRadius"
  | "borderBottomLeftRadius"
  | "borderCollapse"
  | "borderSpacing"
  | "boxShadow"
  | "outline"
  | "outlineWidth"
  | "outlineStyle"
  | "outlineColor"
  | "outlineOffset"
  | "opacity"
  | "overflow"
  | "overflowX"
  | "overflowY"
  | "resize"
  | "visibility"
  | "cursor"
  | "pointerEvents"
  | "userSelect"
  | "transition"
  | "transitionProperty"
  | "transitionDuration"
  | "transitionTimingFunction"
  | "transitionDelay"
  | "transform"
  | "transformOrigin"
  | "animation"
  | "animationName"
  | "animationDuration"
  | "animationTimingFunction"
  | "animationDelay"
  | "animationIterationCount"
  | "animationDirection"
  | "animationFillMode"
  | "animationPlayState"
  | "background"
  | "backgroundImage"
  | "backgroundPosition"
  | "backgroundSize"
  | "backgroundRepeat"
  | "backgroundAttachment"
  | "backgroundClip"
  | "backgroundOrigin"
  | "backgroundBlendMode"
  | "backgroundImageTransform"
  | "colorAdjust"
  | "filter"
  | "backdropFilter"
  | "mixBlendMode"
  | "borderImage"
  | "borderImageSource"
  | "borderImageSlice"
  | "borderImageWidth"
  | "borderImageOutset"
  | "borderImageRepeat"
  | string

export type SxType = Record<SxKeys, string>

// export const sxToStringReduce = (sx: object) => {
//   return Object.entries(sx).reduce((acc, [key, value]) => {
//     return `${acc}${key}:${value};`;
//   }, "");
// };
